name: 'autopep8'
author: 'Zhang Jie'
description: 'Automatically formats Python code to conform to the PEP 8 style guide.'
inputs:
  args:
    description: 'Arguments to pass to autopep8'
    required: true
    default: '--help'
outputs:
  exit-code:
    description: 'The exit code output by autopep8'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/j-z10/autopep8:2.1.0'
  args:
    - ${{ inputs.args }}
branding:
  icon: 'code'  
  color: 'blue'
